version: '3.8'

services:
  leave-management-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_URI=${DB_URI}
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_data: 

networks:
  app-network:
    driver: bridge 